### ISSUE TITLE
Analyze forked repositories

### ISSUE THREAD

**Issue by jrday** [atomist/sdm-pack-aspect#182]
`atomist analyze github repositories` isn't detecting forked repositories.

Test org: https://github.com/xylocarp-whelky
189 forked repos, 1 repo created directly in the org

```bash
$ atomist analyze github repositories
choose repositories to analyze, by owner or query
? GitHub owner of repositories to analyze xylocarp-whelky
? A GitHub search query to choose repositories 
# general 2019-08-24 15:03:28 Analysis result: {
    "repositoriesDetected": 1,
    "projectsDetected": 0,
    "failed": [
      {
        "repoUrl": "https://api.github.com/repos/xylocarp-whelky/blank-repo",
        "whileTryingTo": "clone",
        "message": "Child process 4822 exited with non-zero status 128: /var/folders/l1/h1rth491795_tvrrm8xd4v200000gn/T/atm-3913-3913o8pN9f2G4a3B ==> git 'fetch' '--unshallow'\nfatal: --unshallow on a complete repository does not make sense\n"
      }
    ],
    "keptExisting": [],
    "persistedAnalyses": []
  }
```

**Comment by johnsonr** [comment]
It should be _possible_ to analyze forked repos without error, but I'm not sure it should be the default.

**Comment by jessitron** [comment]
It is possible now, this way:

atomist analyze github by query --query "org:xylocarp-whelky fork:true"

I can add fork:true by default, and then you can use the query syntax to do an org without it

I'm not in favor of making it an explicit option, and gradually building CLI parameters to abstract the GitHub query syntax :-/

**Comment by jrday-fc** [comment]
That works well @jessitron and I agree @johnsonr this should not be the default, but possible.

slight tweak to make that command with query switch work:

`atomist analyze github repositories by query --query "org:xylocarp-whelky fork:true"`

**Comment by jessitron** [comment]
... if you update, the word "repositories" is gone from that command.

OK to close the issue?
